# Generated by Django 2.0.1 on 2018-04-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20180418_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
