# Generated by Django 2.0.1 on 2018-04-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribe', '0003_delete_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
