# Generated by Django 2.0.1 on 2018-04-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
