# Generated by Django 2.0.1 on 2018-04-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Subscribe',
        ),
    ]
