# Generated by Django 2.0.1 on 2018-04-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0007_auto_20180418_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='name',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
