# Generated by Django 2.0.1 on 2018-04-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0008_auto_20180418_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
